### ISSUE TITLE
Avoid re-renders

### ISSUE THREAD

**Issue by jakubszalek** [adamborowski/react-arch-demo#8]
State that store repository list is defined quite high in the tree. 
Currently, changes in the state causes rerenders of Searchbox which is not needed.
Also, number of renders on initial load can be reduced.
Please check what possible solutions can be applied here.

**Comment by adamborowski** [comment]
At least three options are possible:
1.  lift list state down to the list component
2. use React.memo for components that currently re-render unnecessarily. this requires ensuring that data passed as props are not recreated every render (useCallback, useMemo in necessary places...)
3. using something like [react-fast-context](https://www.npmjs.com/package/@passionware/react-fast-context) to effectively connect to some data context

I will choose option 2 as I don't want to refactor the entire project - there was an idea behind keeping the state at the root level of page components.


I will also change a bit around useSearchClient that causes additional re-renders (because of useEffects), or just use react-query for managing the state.

**Comment by adamborowski** [comment]
@mrcodegit please check the linked PR #10
