### ISSUE TITLE
Misc. smaller issues

### ISSUE THREAD

**Issue by jakubszalek** [adamborowski/react-arch-demo#9]
I noticed some minor issues that can be handled to make code cleaner:
1. Most of API related utilities depends on `SearchClient` interface - this kind of utilities should be "data-agnostic" and be able to reuse every app module.
2. Application uses both REST and GQL endpoints. Is it possible to stick to only one type to reduce complexity?
3. "eslint-disable-next-line react-hooks/exhaustive-deps" present in the code. You shouldn't need to disable any eslint rules in such a simple app. Adding dependencies required by `useEffect` causes endless loop. Please take another look on state changes - most probably there is an issue that might be a cause.

**Comment by adamborowski** [comment]
Re: 1

I think I understand where your question came from.
If we talk about withDelay, withFailure, withLoading, they might look like those utilities are data-specific, but if we look at their implementation, they implement a method that only intercepts another client (let's call it higher order client)
They are data-agnostic because the data is abstracted by generic parameter.

I think it might be more clear if I show the original version I refactored from.

In other projects we had many similar modules that were utilizing CRUD functionality, they were different only by the kind of IO: fetch, local storage, etc... also were talking to different data structures (so they had to adapt one structure to client data structure). But despite that differences, all applications needed to fetch all items, fetch specific item, update, create and delete one.

So our client was called `CrudClient` and was exposing various methods to interact with IO: getAll, get, insert, delete, update.

Then, for easy composition, we had utilities for any CrudClient, adding one specific behavior, for example:
```tsx
export const withDelay = <T>(
  client: CrudClient<T>,
  delayMsc: number
): CrudClient<T> => {
  return {
    getAll: async () => {
      const result = await client.getAll();
      await delay(delayMsc);
      return result;
    },
    insert: async (payload) => {
      await client.insert(payload);
      return delay(delayMsc);
    },
    ...
  };
};
```

So if I had to make this utility not depending on `CrudClient`, I have nothing to do in this utility, they are pretty simple: proxying.

Now, talking back about `SearchClient` it may look confusing, so maybe it was better to have just a function behind `SearchClient`:
```tsx
export type SearchClient<T> = (query: string, ...) => T[]
```
so our data fetching utilities would look really simple and definitely data-agnostic:
```ts
export const withDelay = <T extends (query:string)=>unknown)> (api: T) =>  async (query) => {
    const result = await api(query);
    await delay(delayMsc);
    return result;
  }
```

The only problem is that this version of SearchClient is not that easy to extend as CrudClient - which allows to have mulitple objects.

Sorry for the long explanation, but after I provided some context, what would you say again about this point?
Should we leave it or simplify the definition of `SearchClient` as showed above? Or you was talking about something else?
